import { Space_Mono} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";


const spaceMono = Space_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-mono antialiased flex-col min-h-screen text-green-400` }
      >
        <>
        <Header></Header>
        <main className="flex-grow">
          {children}
        </main>
        
        <Footer></Footer>
        </>
      </body>
    </html>
  );
}
